### ISSUE TITLE
Test warning

### ISSUE THREAD

**Issue by maeste** [wise-agents/wise-agents#277]
Even if tests passed I have this warning with PR #267 
It needs some investigation, but before we need to have #276 to exclude that one is the route cause

tests/wiseagents/vectordb/test_PGVectorLangChainWiseAgentVectorDB.py: 4 warnings
  /home/maeste/project/wise-agents/.venv/lib64/python3.12/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
    warnings.warn(

tests/wiseagents/agents/test_sequential_coordinator.py::test_sequential_coordinator
  /home/maeste/project/wise-agents/.venv/lib64/python3.12/site-packages/_pytest/threadexception.py:82: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-15 (__receiver_loop)
  
  Traceback (most recent call last):
    File "/usr/lib64/python3.12/threading.py", line 1075, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.12/threading.py", line 1012, in run
      self._target(*self._args, **self._kwargs)
    File "/home/maeste/project/wise-agents/.venv/lib64/python3.12/site-packages/stomp/transport.py", line 341, in __receiver_loop
      self.process_frame(f, frame)
    File "/home/maeste/project/wise-agents/.venv/lib64/python3.12/site-packages/stomp/transport.py", line 190, in process_frame
      self.notify(frame_type, f)
    File "/home/maeste/project/wise-agents/.venv/lib64/python3.12/site-packages/stomp/transport.py", line 243, in notify
      notify_func(frame)
    File "/home/maeste/project/wise-agents/.venv/lib64/python3.12/site-packages/wiseagents/transports/stomp.py", line 30, in on_message
      self.transport.request_receiver(yaml.load(message.body, yaml.Loader))
    File "/home/maeste/project/wise-agents/.venv/lib64/python3.12/site-packages/wiseagents/agents/collaboration_wise_agents.py", line 418, in process_request
      messages = ctx.llm_chat_completion[chat_id]
                 ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  KeyError: '218a262f-cd9e-4876-9fcd-c852f882ada3'
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/wiseagents/vectordb/test_PGVectorLangChainWiseAgentVectorDB.py::test_delete_documents
tests/wiseagents/vectordb/test_PGVectorLangChainWiseAgentVectorDB.py::test_delete_documents
  /home/maeste/project/wise-agents/.venv/lib64/python3.12/site-packages/neo4j/_sync/driver.py:526: DeprecationWarning: Relying on Driver's destructor to close the session is deprecated. Please make sure to close the session. Use it as a context (`with` statement) or make sure to call `.close()` explicitly. Future versions of the driver will not close drivers automatically.
    _deprecation_warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

**Comment by fjuma** [comment]
https://github.com/wise-agents/wise-agents/issues/131 track this as well. I'll close that one since we have more details in this issue.

**Comment by fjuma** [comment]
https://github.com/wise-agents/wise-agents/pull/371 fixes the clean_up_tokenization_spaces warning.

Will create a separate issue for the neo4j warning and will close this one.
